package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TcitamedicaId generated by hbm2java
 */
public class TcitamedicaId  implements java.io.Serializable {

     private int tpacienteDni;
     private int tdispCitaMedCodDispo;
     private int tdispCitaMedCodMedico;
     private Date fechaCitaCreada;

    public TcitamedicaId() {
    }

    public TcitamedicaId(int tpacienteDni, int tdispCitaMedCodDispo, int tdispCitaMedCodMedico, Date fechaCitaCreada) {
       this.tpacienteDni = tpacienteDni;
       this.tdispCitaMedCodDispo = tdispCitaMedCodDispo;
       this.tdispCitaMedCodMedico = tdispCitaMedCodMedico;
       this.fechaCitaCreada = fechaCitaCreada;
    }
   
    public int getTpacienteDni() {
        return this.tpacienteDni;
    }
    
    public void setTpacienteDni(int tpacienteDni) {
        this.tpacienteDni = tpacienteDni;
    }
    public int getTdispCitaMedCodDispo() {
        return this.tdispCitaMedCodDispo;
    }
    
    public void setTdispCitaMedCodDispo(int tdispCitaMedCodDispo) {
        this.tdispCitaMedCodDispo = tdispCitaMedCodDispo;
    }
    public int getTdispCitaMedCodMedico() {
        return this.tdispCitaMedCodMedico;
    }
    
    public void setTdispCitaMedCodMedico(int tdispCitaMedCodMedico) {
        this.tdispCitaMedCodMedico = tdispCitaMedCodMedico;
    }
    public Date getFechaCitaCreada() {
        return this.fechaCitaCreada;
    }
    
    public void setFechaCitaCreada(Date fechaCitaCreada) {
        this.fechaCitaCreada = fechaCitaCreada;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TcitamedicaId) ) return false;
		 TcitamedicaId castOther = ( TcitamedicaId ) other; 
         
		 return (this.getTpacienteDni()==castOther.getTpacienteDni())
 && (this.getTdispCitaMedCodDispo()==castOther.getTdispCitaMedCodDispo())
 && (this.getTdispCitaMedCodMedico()==castOther.getTdispCitaMedCodMedico())
 && ( (this.getFechaCitaCreada()==castOther.getFechaCitaCreada()) || ( this.getFechaCitaCreada()!=null && castOther.getFechaCitaCreada()!=null && this.getFechaCitaCreada().equals(castOther.getFechaCitaCreada()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTpacienteDni();
         result = 37 * result + this.getTdispCitaMedCodDispo();
         result = 37 * result + this.getTdispCitaMedCodMedico();
         result = 37 * result + ( getFechaCitaCreada() == null ? 0 : this.getFechaCitaCreada().hashCode() );
         return result;
   }   


}


