package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TdetallehistoriaId generated by hbm2java
 */
public class TdetallehistoriaId  implements java.io.Serializable {


     private Date fechaAtencion;
     private int thistoriaPacienteDni;

    public TdetallehistoriaId() {
    }

    public TdetallehistoriaId(Date fechaAtencion, int thistoriaPacienteDni) {
       this.fechaAtencion = fechaAtencion;
       this.thistoriaPacienteDni = thistoriaPacienteDni;
    }
   
    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    public int getThistoriaPacienteDni() {
        return this.thistoriaPacienteDni;
    }
    
    public void setThistoriaPacienteDni(int thistoriaPacienteDni) {
        this.thistoriaPacienteDni = thistoriaPacienteDni;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TdetallehistoriaId) ) return false;
		 TdetallehistoriaId castOther = ( TdetallehistoriaId ) other; 
         
		 return ( (this.getFechaAtencion()==castOther.getFechaAtencion()) || ( this.getFechaAtencion()!=null && castOther.getFechaAtencion()!=null && this.getFechaAtencion().equals(castOther.getFechaAtencion()) ) )
 && (this.getThistoriaPacienteDni()==castOther.getThistoriaPacienteDni());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFechaAtencion() == null ? 0 : this.getFechaAtencion().hashCode() );
         result = 37 * result + this.getThistoriaPacienteDni();
         return result;
   }   


}


