package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tdisponibilidad generated by hbm2java
 */
public class Tdisponibilidad  implements java.io.Serializable {


     private int codDispo;
     private String dia;
     private Date horaIni;
     private Date horaFin;
     private Set tdisponibilidadcitamedicas = new HashSet(0);

    public Tdisponibilidad() {
    }

	
    public Tdisponibilidad(int codDispo, String dia, Date horaIni, Date horaFin) {
        this.codDispo = codDispo;
        this.dia = dia;
        this.horaIni = horaIni;
        this.horaFin = horaFin;
    }
    public Tdisponibilidad(int codDispo, String dia, Date horaIni, Date horaFin, Set tdisponibilidadcitamedicas) {
       this.codDispo = codDispo;
       this.dia = dia;
       this.horaIni = horaIni;
       this.horaFin = horaFin;
       this.tdisponibilidadcitamedicas = tdisponibilidadcitamedicas;
    }
   
    public int getCodDispo() {
        return this.codDispo;
    }
    
    public void setCodDispo(int codDispo) {
        this.codDispo = codDispo;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public Date getHoraIni() {
        return this.horaIni;
    }
    
    public void setHoraIni(Date horaIni) {
        this.horaIni = horaIni;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Set getTdisponibilidadcitamedicas() {
        return this.tdisponibilidadcitamedicas;
    }
    
    public void setTdisponibilidadcitamedicas(Set tdisponibilidadcitamedicas) {
        this.tdisponibilidadcitamedicas = tdisponibilidadcitamedicas;
    }




}


