package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tenfermedad generated by hbm2java
 */
public class Tenfermedad  implements java.io.Serializable {


     private int codEnfer;
     private String nombre;
     private String descripcion;
     private Set thistoriaclinicas = new HashSet(0);

    public Tenfermedad() {
    }

    public Tenfermedad(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    
    public Tenfermedad(int codEnfer, String nombre) {
        this.codEnfer = codEnfer;
        this.nombre = nombre;
    }
    public Tenfermedad(int codEnfer, String nombre, String descripcion, Set thistoriaclinicas) {
       this.codEnfer = codEnfer;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.thistoriaclinicas = thistoriaclinicas;
    }
   
    public int getCodEnfer() {
        return this.codEnfer;
    }
    
    public void setCodEnfer(int codEnfer) {
        this.codEnfer = codEnfer;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getThistoriaclinicas() {
        return this.thistoriaclinicas;
    }
    
    public void setThistoriaclinicas(Set thistoriaclinicas) {
        this.thistoriaclinicas = thistoriaclinicas;
    }




}


