package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tespecialidad generated by hbm2java
 */
public class Tespecialidad  implements java.io.Serializable {


     private int codEspe;
     private String nombre;
     private String descripcion;
     private double costo;
     private Set tdisponibilidadcitamedicas = new HashSet(0);

    public Tespecialidad() {
    }

	
    public Tespecialidad(int codEspe, String nombre, double costo) {
        this.codEspe = codEspe;
        this.nombre = nombre;
        this.costo = costo;
    }
    public Tespecialidad(int codEspe, String nombre, String descripcion, double costo, Set tdisponibilidadcitamedicas) {
       this.codEspe = codEspe;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.costo = costo;
       this.tdisponibilidadcitamedicas = tdisponibilidadcitamedicas;
    }
   
    public int getCodEspe() {
        return this.codEspe;
    }
    
    public void setCodEspe(int codEspe) {
        this.codEspe = codEspe;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }
    public Set getTdisponibilidadcitamedicas() {
        return this.tdisponibilidadcitamedicas;
    }
    
    public void setTdisponibilidadcitamedicas(Set tdisponibilidadcitamedicas) {
        this.tdisponibilidadcitamedicas = tdisponibilidadcitamedicas;
    }




}


