package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Texamenmedicosolicitado generated by hbm2java
 */
public class Texamenmedicosolicitado  implements java.io.Serializable {


     private TexamenmedicosolicitadoId id;
     private Tdetallehistoria tdetallehistoria;
     private Texamenmedico texamenmedico;
     private Date fechaEntrega;
     private String estado;
     private String observacion;
     private double costo;

    public Texamenmedicosolicitado() {
    }

	
    public Texamenmedicosolicitado(TexamenmedicosolicitadoId id, Tdetallehistoria tdetallehistoria, Texamenmedico texamenmedico, Date fechaEntrega, String estado, double costo) {
        this.id = id;
        this.tdetallehistoria = tdetallehistoria;
        this.texamenmedico = texamenmedico;
        this.fechaEntrega = fechaEntrega;
        this.estado = estado;
        this.costo = costo;
    }
    public Texamenmedicosolicitado(TexamenmedicosolicitadoId id, Tdetallehistoria tdetallehistoria, Texamenmedico texamenmedico, Date fechaEntrega, String estado, String observacion, double costo) {
       this.id = id;
       this.tdetallehistoria = tdetallehistoria;
       this.texamenmedico = texamenmedico;
       this.fechaEntrega = fechaEntrega;
       this.estado = estado;
       this.observacion = observacion;
       this.costo = costo;
    }
   
    public TexamenmedicosolicitadoId getId() {
        return this.id;
    }
    
    public void setId(TexamenmedicosolicitadoId id) {
        this.id = id;
    }
    public Tdetallehistoria getTdetallehistoria() {
        return this.tdetallehistoria;
    }
    
    public void setTdetallehistoria(Tdetallehistoria tdetallehistoria) {
        this.tdetallehistoria = tdetallehistoria;
    }
    public Texamenmedico getTexamenmedico() {
        return this.texamenmedico;
    }
    
    public void setTexamenmedico(Texamenmedico texamenmedico) {
        this.texamenmedico = texamenmedico;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }




}


