package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Texamenmedico generated by hbm2java
 */
public class Texamenmedico  implements java.io.Serializable {


     private int codExamenMedico;
     private String nombre;
     private String descripcion;
     private double costo;
     private Set texamenmedicosolicitados = new HashSet(0);

    public Texamenmedico() {
    }

	
    public Texamenmedico(int codExamenMedico, String nombre, double costo) {
        this.codExamenMedico = codExamenMedico;
        this.nombre = nombre;
        this.costo = costo;
    }
    public Texamenmedico(int codExamenMedico, String nombre, String descripcion, double costo, Set texamenmedicosolicitados) {
       this.codExamenMedico = codExamenMedico;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.costo = costo;
       this.texamenmedicosolicitados = texamenmedicosolicitados;
    }
   
    public int getCodExamenMedico() {
        return this.codExamenMedico;
    }
    
    public void setCodExamenMedico(int codExamenMedico) {
        this.codExamenMedico = codExamenMedico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getCosto() {
        return this.costo;
    }
    
    public void setCosto(double costo) {
        this.costo = costo;
    }
    public Set getTexamenmedicosolicitados() {
        return this.texamenmedicosolicitados;
    }
    
    public void setTexamenmedicosolicitados(Set texamenmedicosolicitados) {
        this.texamenmedicosolicitados = texamenmedicosolicitados;
    }




}


