package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TexamenmedicosolicitadoId generated by hbm2java
 */
public class TexamenmedicosolicitadoId  implements java.io.Serializable {


     private Date tdhFechaAtencion;
     private int tdhThistoriaPacienteDni;
     private int temCodExamenMedico;

    public TexamenmedicosolicitadoId() {
    }

    public TexamenmedicosolicitadoId(Date tdhFechaAtencion, int tdhThistoriaPacienteDni, int temCodExamenMedico) {
       this.tdhFechaAtencion = tdhFechaAtencion;
       this.tdhThistoriaPacienteDni = tdhThistoriaPacienteDni;
       this.temCodExamenMedico = temCodExamenMedico;
    }
   
    public Date getTdhFechaAtencion() {
        return this.tdhFechaAtencion;
    }
    
    public void setTdhFechaAtencion(Date tdhFechaAtencion) {
        this.tdhFechaAtencion = tdhFechaAtencion;
    }
    public int getTdhThistoriaPacienteDni() {
        return this.tdhThistoriaPacienteDni;
    }
    
    public void setTdhThistoriaPacienteDni(int tdhThistoriaPacienteDni) {
        this.tdhThistoriaPacienteDni = tdhThistoriaPacienteDni;
    }
    public int getTemCodExamenMedico() {
        return this.temCodExamenMedico;
    }
    
    public void setTemCodExamenMedico(int temCodExamenMedico) {
        this.temCodExamenMedico = temCodExamenMedico;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TexamenmedicosolicitadoId) ) return false;
		 TexamenmedicosolicitadoId castOther = ( TexamenmedicosolicitadoId ) other; 
         
		 return ( (this.getTdhFechaAtencion()==castOther.getTdhFechaAtencion()) || ( this.getTdhFechaAtencion()!=null && castOther.getTdhFechaAtencion()!=null && this.getTdhFechaAtencion().equals(castOther.getTdhFechaAtencion()) ) )
 && (this.getTdhThistoriaPacienteDni()==castOther.getTdhThistoriaPacienteDni())
 && (this.getTemCodExamenMedico()==castOther.getTemCodExamenMedico());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTdhFechaAtencion() == null ? 0 : this.getTdhFechaAtencion().hashCode() );
         result = 37 * result + this.getTdhThistoriaPacienteDni();
         result = 37 * result + this.getTemCodExamenMedico();
         return result;
   }   


}


