package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Thistoriaclinica generated by hbm2java
 */
public class Thistoriaclinica  implements java.io.Serializable {


     private int tpacienteDni;
     private Tpaciente tpaciente;
     private Date fechaCreacion;
     private int numHistoria;
     private Set tdetallehistorias = new HashSet(0);
     private Set tenfermedads = new HashSet(0);

    public Thistoriaclinica() {
    }

    public Thistoriaclinica(Tpaciente tpaciente, Date fechaCreacion){
        this.tpaciente = tpaciente;
        this.fechaCreacion = fechaCreacion;        
    }
	
    public Thistoriaclinica(Tpaciente tpaciente, Date fechaCreacion, int numHistoria) {
        this.tpaciente = tpaciente;
        this.fechaCreacion = fechaCreacion;
        this.numHistoria = numHistoria;
    }
    public Thistoriaclinica(Tpaciente tpaciente, Date fechaCreacion, int numHistoria, Set tdetallehistorias, Set tenfermedads) {
       this.tpaciente = tpaciente;
       this.fechaCreacion = fechaCreacion;
       this.numHistoria = numHistoria;
       this.tdetallehistorias = tdetallehistorias;
       this.tenfermedads = tenfermedads;
    }
   
    public int getTpacienteDni() {
        return this.tpacienteDni;
    }
    
    public void setTpacienteDni(int tpacienteDni) {
        this.tpacienteDni = tpacienteDni;
    }
    public Tpaciente getTpaciente() {
        return this.tpaciente;
    }
    
    public void setTpaciente(Tpaciente tpaciente) {
        this.tpaciente = tpaciente;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public int getNumHistoria() {
        return this.numHistoria;
    }
    
    public void setNumHistoria(int numHistoria) {
        this.numHistoria = numHistoria;
    }
    public Set getTdetallehistorias() {
        return this.tdetallehistorias;
    }
    
    public void setTdetallehistorias(Set tdetallehistorias) {
        this.tdetallehistorias = tdetallehistorias;
    }
    public Set getTenfermedads() {
        return this.tenfermedads;
    }
    
    public void setTenfermedads(Set tenfermedads) {
        this.tenfermedads = tenfermedads;
    }




}


