package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tmedico generated by hbm2java
 */
public class Tmedico  implements java.io.Serializable {


     private int codMedico;
     private String nombres;
     private String apellidos;
     private Set tobservacionmedicas = new HashSet(0);
     private Set tdisponibilidadcitamedicas = new HashSet(0);

    public Tmedico() {
    }

	
    public Tmedico(int codMedico, String nombres, String apellidos) {
        this.codMedico = codMedico;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Tmedico(int codMedico, String nombres, String apellidos, Set tobservacionmedicas, Set tdisponibilidadcitamedicas) {
       this.codMedico = codMedico;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.tobservacionmedicas = tobservacionmedicas;
       this.tdisponibilidadcitamedicas = tdisponibilidadcitamedicas;
    }
   
    public int getCodMedico() {
        return this.codMedico;
    }
    
    public void setCodMedico(int codMedico) {
        this.codMedico = codMedico;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Set getTobservacionmedicas() {
        return this.tobservacionmedicas;
    }
    
    public void setTobservacionmedicas(Set tobservacionmedicas) {
        this.tobservacionmedicas = tobservacionmedicas;
    }
    public Set getTdisponibilidadcitamedicas() {
        return this.tdisponibilidadcitamedicas;
    }
    
    public void setTdisponibilidadcitamedicas(Set tdisponibilidadcitamedicas) {
        this.tdisponibilidadcitamedicas = tdisponibilidadcitamedicas;
    }




}


