package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tobservacionmedica generated by hbm2java
 */
public class Tobservacionmedica  implements java.io.Serializable {


     private TobservacionmedicaId id;
     private Tdetallehistoria tdetallehistoria;
     private Tmedico tmedico;
     private String patologia;
     private String medPrescritos;
     private String diagnostico;
     private Date fechaSintoma;

    public Tobservacionmedica() {
    }

	
    public Tobservacionmedica(Tdetallehistoria tdetallehistoria, Tmedico tmedico, String diagnostico, Date fechaSintoma) {
        this.tdetallehistoria = tdetallehistoria;
        this.tmedico = tmedico;
        this.diagnostico = diagnostico;
        this.fechaSintoma = fechaSintoma;
    }
    public Tobservacionmedica(Tdetallehistoria tdetallehistoria, Tmedico tmedico, String patologia, String medPrescritos, String diagnostico, Date fechaSintoma) {
       this.tdetallehistoria = tdetallehistoria;
       this.tmedico = tmedico;
       this.patologia = patologia;
       this.medPrescritos = medPrescritos;
       this.diagnostico = diagnostico;
       this.fechaSintoma = fechaSintoma;
    }
   
    public TobservacionmedicaId getId() {
        return this.id;
    }
    
    public void setId(TobservacionmedicaId id) {
        this.id = id;
    }
    public Tdetallehistoria getTdetallehistoria() {
        return this.tdetallehistoria;
    }
    
    public void setTdetallehistoria(Tdetallehistoria tdetallehistoria) {
        this.tdetallehistoria = tdetallehistoria;
    }
    public Tmedico getTmedico() {
        return this.tmedico;
    }
    
    public void setTmedico(Tmedico tmedico) {
        this.tmedico = tmedico;
    }
    public String getPatologia() {
        return this.patologia;
    }
    
    public void setPatologia(String patologia) {
        this.patologia = patologia;
    }
    public String getMedPrescritos() {
        return this.medPrescritos;
    }
    
    public void setMedPrescritos(String medPrescritos) {
        this.medPrescritos = medPrescritos;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public Date getFechaSintoma() {
        return this.fechaSintoma;
    }
    
    public void setFechaSintoma(Date fechaSintoma) {
        this.fechaSintoma = fechaSintoma;
    }




}


