package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tpaciente generated by hbm2java
 */
public class Tpaciente  implements java.io.Serializable {


     private int dni;
     private String nombres;
     private String apellidos;
     private String sexo;
     private String estadoCivil;
     private Date fechaNac;
     private String lugarNac;
     private String direccion;
     private Integer celular;
     private Thistoriaclinica thistoriaclinica;
     private Set tcitamedicas = new HashSet(0);

    public Tpaciente() {
       this.dni = 0;
       this.nombres = "";
       this.apellidos = "";
       this.sexo = "";
       this.estadoCivil = "";
       this.fechaNac = null;
       this.lugarNac = "";
       this.direccion = "";
       this.celular = 0;
       this.thistoriaclinica = null;
       this.tcitamedicas = null;
    }

	
    public Tpaciente(int dni, String nombres, String apellidos, String sexo) {
        this.dni = dni;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.sexo = sexo;
    }
    public Tpaciente(int dni, String nombres, String apellidos, String sexo, String estadoCivil, Date fechaNac, String lugarNac, String direccion, Integer celular, Thistoriaclinica thistoriaclinica, Set tcitamedicas) {
       this.dni = dni;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.sexo = sexo;
       this.estadoCivil = estadoCivil;
       this.fechaNac = fechaNac;
       this.lugarNac = lugarNac;
       this.direccion = direccion;
       this.celular = celular;
       this.thistoriaclinica = thistoriaclinica;
       this.tcitamedicas = tcitamedicas;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getLugarNac() {
        return this.lugarNac;
    }
    
    public void setLugarNac(String lugarNac) {
        this.lugarNac = lugarNac;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public Thistoriaclinica getThistoriaclinica() {
        return this.thistoriaclinica;
    }
    
    public void setThistoriaclinica(Thistoriaclinica thistoriaclinica) {
        this.thistoriaclinica = thistoriaclinica;
    }
    public Set getTcitamedicas() {
        return this.tcitamedicas;
    }
    
    public void setTcitamedicas(Set tcitamedicas) {
        this.tcitamedicas = tcitamedicas;
    }




}


