package pe.com.siam.model.pojo;
// Generated 12/07/2015 07:32:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Trol generated by hbm2java
 */
public class Trol  implements java.io.Serializable {


     private int idtrol;
     private String nombre;
     private Set toperacions = new HashSet(0);
     private Set tusuarios = new HashSet(0);

    public Trol() {
    }

	
    public Trol(int idtrol) {
        this.idtrol = idtrol;
    }
    public Trol(int idtrol, String nombre, Set toperacions, Set tusuarios) {
       this.idtrol = idtrol;
       this.nombre = nombre;
       this.toperacions = toperacions;
       this.tusuarios = tusuarios;
    }
   
    public int getIdtrol() {
        return this.idtrol;
    }
    
    public void setIdtrol(int idtrol) {
        this.idtrol = idtrol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getToperacions() {
        return this.toperacions;
    }
    
    public void setToperacions(Set toperacions) {
        this.toperacions = toperacions;
    }
    public Set getTusuarios() {
        return this.tusuarios;
    }
    
    public void setTusuarios(Set tusuarios) {
        this.tusuarios = tusuarios;
    }




}


