package pe.com.siam.model.pojo;
// Generated 06/06/2015 01:03:46 PM by Hibernate Tools 4.3.1



/**
 * Ttriaje generated by hbm2java
 */
public class Ttriaje  implements java.io.Serializable {


     private TtriajeId id;
     private Tdetallehistoria tdetallehistoria;
     private double peso;
     private double talla;
     private double pulso;
     private double presionDiastolica;
     private double presionSistolica;
     private String observacion;

    public Ttriaje() {
    }

	
    public Ttriaje(Tdetallehistoria tdetallehistoria, double peso, double talla, double pulso, double presionDiastolica, double presionSistolica) {
        this.tdetallehistoria = tdetallehistoria;
        this.peso = peso;
        this.talla = talla;
        this.pulso = pulso;
        this.presionDiastolica = presionDiastolica;
        this.presionSistolica = presionSistolica;
    }
    public Ttriaje(Tdetallehistoria tdetallehistoria, double peso, double talla, double pulso, double presionDiastolica, double presionSistolica, String observacion) {
       this.tdetallehistoria = tdetallehistoria;
       this.peso = peso;
       this.talla = talla;
       this.pulso = pulso;
       this.presionDiastolica = presionDiastolica;
       this.presionSistolica = presionSistolica;
       this.observacion = observacion;
    }
   
    public TtriajeId getId() {
        return this.id;
    }
    
    public void setId(TtriajeId id) {
        this.id = id;
    }
    public Tdetallehistoria getTdetallehistoria() {
        return this.tdetallehistoria;
    }
    
    public void setTdetallehistoria(Tdetallehistoria tdetallehistoria) {
        this.tdetallehistoria = tdetallehistoria;
    }
    public double getPeso() {
        return this.peso;
    }
    
    public void setPeso(double peso) {
        this.peso = peso;
    }
    public double getTalla() {
        return this.talla;
    }
    
    public void setTalla(double talla) {
        this.talla = talla;
    }
    public double getPulso() {
        return this.pulso;
    }
    
    public void setPulso(double pulso) {
        this.pulso = pulso;
    }
    public double getPresionDiastolica() {
        return this.presionDiastolica;
    }
    
    public void setPresionDiastolica(double presionDiastolica) {
        this.presionDiastolica = presionDiastolica;
    }
    public double getPresionSistolica() {
        return this.presionSistolica;
    }
    
    public void setPresionSistolica(double presionSistolica) {
        this.presionSistolica = presionSistolica;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


